field: abc69f2d-8d8b-439b-a1f7-2cf3a3adcce4 # Feature Block
fieldLayouts:
  0454d925-f982-445b-8910-0b64d5e75ccc:
    tabs:
      -
        elements:
          -
            fieldUid: cc1e2149-d462-42a8-8f05-eaa6584ae80e # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a69e9c89-2d6e-4797-8d44-e30a9656eda0 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4e4ede3b-cc00-441c-be5f-744bb101f514 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4e4ede3b-cc00-441c-be5f-744bb101f514: # Excerpt
    contentColumnType: text
    fieldGroup: null
    handle: excerpt
    instructions: ''
    name: Excerpt
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a69e9c89-2d6e-4797-8d44-e30a9656eda0: # Heading
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cc1e2149-d462-42a8-8f05-eaa6584ae80e: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:56b430a4-3a93-4d23-b7fd-1b57b6deda22' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:56b430a4-3a93-4d23-b7fd-1b57b6deda22' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:56b430a4-3a93-4d23-b7fd-1b57b6deda22' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: feature
name: feature
sortOrder: 1
