fieldLayouts:
  75060241-5f67-4382-a4bb-e06cb780135b:
    tabs:
      -
        elements:
          -
            fieldUid: 0ceb626a-272d-4f63-b3a4-ab88ef55cf61 # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b4ad8e86-0a39-423a-a0cc-6a7d62e9e846 # Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Office'
        sortOrder: 1
handle: mainOffice
name: 'Main Office'
